- name: Load Mongo Schema
  when: schema_setup =="mongo"
  block:
    - name: Copy mongo.repo file
      ansible.builtin.copy:
       src: mongo.repo
       dest: /etc/yum.repos.d/mongo.repo

    - name: Install MongoDb Client
      ansible.builtin.yum:
       name: mongodb-org-shell
       state: installed

    - name: Load Schema
      ansible.builtin.shell: mongo --host {{ lookup('aws_ssm', 'dev.catalogue.mongo_endpoint', region='us-east-1' ) }} </app/schema/{{component}}.js


#  func_print_head "load schema"
#  mysql -h mysql-dev.pdevops.online -uroot -p${mysql_root_password} < /app/schema/${component}.sql &>>$log_file
#  func_status_check $?
- name: Install Mysql
  when: schema_setup =="mysql"
  block:
    - name: Install Mysql
      ansible.builtin.yum:
        name: mysql

    - name: Load Mysql Schema
      ansible.builtin.shell: mysql -h {{ lookup('aws_ssm', 'dev.shipping.db_host', region='us-east-1' ) }} -u{{ lookup('aws_ssm', 'dev.shipping.db_user', region='us-east-1' ) }} -p{{ lookup('aws_ssm', 'dev.shipping.db_password', region='us-east-1' ) }} < /app/schema/{{ component }}.sql


